config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { registrations: 'registrations' }

    get '/', to: 'home#index'

    resources :lists do
      member do
        patch :move
      end
    end
    
    resources :cards do
      member do
        patch :move
      end
    end
  
    devise_scope :user do
      root :to => 'devise/sessions#new'
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    acts_as_list scope: :list

    belongs_to :list
  
    validates :name, presence: true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user

    acts_as_list

    has_many :cards, -> { order(position: :asc) }, dependent: :destroy
  
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/RegistrationsController.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource_or_scope)
        '/lists'
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save

        ActionCable.server.broadcast "board", { commit: 'addCard', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)

        ActionCable.server.broadcast "board", { commit: 'editCard', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @card.update(card_params)
    ActionCable.server.broadcast "board", { commit: 'moveCard', payload: render_to_string(:show, format: :json) }
    render action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:list_id, :name, :position)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :move]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.order(position: :asc)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user = User.find(current_user.id)
    respond_to do |format|
      if @list.save

        ActionCable.server.broadcast "board", { commit: 'addList', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @list.insert_at(list_params[:position].to_i)
    @list.user = User.find(current_user.id)
    ActionCable.server.broadcast "board", { commit: 'moveList', payload: render_to_string(:show, format: :json) }
    render action: :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/application/_footer-fixed.html.erb
  <footer class="footer footer-absolute purple">
    <div class="container text-center py-4">
      <span class="text-white">
        © <%= Date.today.year %> - GO Tasks. <br> Made with <3 by Ítalo and Tiago
      </span>
    </div>
  </footer>

app/views/application/_footer.html.erb
  <footer class="footer purple">
    <div class="container text-center py-4">
      <span class="text-white">
        © <%= Date.today.year %> - GO Tasks. <br> Made with <3 by Ítalo and Tiago
      </span>
    </div>
  </footer>

app/views/application/_navbar.html.erb
    <nav class="navbar purple navbar-expand-md navbar-dark">
        <div class="container text-white"><%= link_to "GO", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMain">
                <ul class="navbar-nav mr-auto mt-2 mt-md-0">
                    <li class="nav-item"><a class="nav-link" href="https://gitlab.com/tsrrodrigues/ep3/">About</a>
                    </li>
                </ul>
        <ul class="navbar-nav">
        <% if user_signed_in? %>
            <li class="nav-item"><%= link_to current_user.name, lists_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
            <% else %>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
        <% end %>
                </ul>
            </div>
        </div>
    </nav>

    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list %>
    <%= form.text_field :list %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>List</th>
      <th>Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.list_id %></td>
        <td><%= card.name %></td>
        <td><%= card.position %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @card.list %>
</p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @card.position %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/home/index.html.erb
<body>
  <%= render 'navbar' %>

  <div class="banner purple-light position-relative overflow-hidden p-3 p-md-5 text-center">
  <div class="col-md-5 p-lg-5 mx-auto my-5 text-white">
    <h1 class="display-4 font-weight-normal">GO Tasks</h1>
    <p class="lead font-weight-normal">Organize and prioritize your tasks with lists and cards.</p> <br>
      <%= link_to "Start now", user_session_path, class: "btn btn-primary" %></li>
  </div>
  </div>
  <div class="d-md-flex flex-md-equal w-100 my-md-3">
  <div class="bg-light box pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Things To Do</h2>
      <p class="lead">Put cards to do.</p>
    </div>
    <div class="list-example gradient mx-auto" style="width: 60%; height: 300px; border-radius: 20px;">
      <h3 class="name">things to do</h3>
      <div class="card card-body mb-4">do homework</div>
      <div class="card card-body mb-4">go to job</div>
      <div class="card card-body mb-4">study</div>
    </div>
  </div>
  <div class="bg-light box pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Doing</h2>
      <p class="lead">Put cards that you're doing.</p>
    </div>
    <div class="list-example gradient mx-auto" style="width: 60%; height: 300px; border-radius: 20px;">
      <h3 class="name">doing</h3>
      <div class="card card-body mb-4">playing</div>
      <div class="card card-body mb-4">watching netflix</div>
      <div class="card card-body mb-4">ep3</div>
    </div>
  </div>
  </div>
  <div class="d-md-flex flex-md-equal w-100 my-md-3">
  <div class="bg-light box pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 p-3">
      <h2 class="display-5">Done</h2>
      <p class="lead">Put cards that you done.</p>
    </div>
    <div class="list-example gradient mx-auto" style="width: 60%; height: 300px; border-radius: 20px;">
      <h3 class="name">done</h3>
      <div class="card card-body mb-4">nothing is done</div>
      <div class="card card-body mb-4">&nbsp;</div>
      <div class="card card-body mb-4">&nbsp;</div>
    </div>
  </div>
  <div class="bg-light box pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
    <div class="my-3 py-3">
      <h2 class="display-5">Another list.</h2>
      <p class="lead">Put anything you want to. Rename any card.</p>
    </div>
    <div class="list-example gradient mx-auto" style="width: 60%; height: 300px; border-radius: 20px;">
      <h3 class="name">my list</h3>
      <div class="card card-body mb-4">watch oscar</div>
      <div class="card card-body mb-4">listen watermelon sugar</div>
      <div class="card card-body mb-4">&nbsp;</div>
    </div>
  </div>
  </div>

  <%= render 'footer' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="Ítalo Alves and Tiago Samuel">
  
  <title>GO Tasks</title>
  
  <!-- Rails core -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <!-- Favicons -->
	<meta name="msapplication-navbutton-color" content="#895f9d">
	<meta name="theme-color" content="#895f9d">
  
</head>

  <%= yield %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<body class="lists">
  <%= render 'navbar' %>

  <div class="container-fluid">
    <div class="mt-3">
      <%= tag.div id: :boards, data: { user: User.find(current_user.id).to_json(:include => { :lists => { :include => { :cards => {} } } }) } %>
    </div>
  </div>
</body>

</html>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @list.position %>
</p>

<p>
  <strong>User_ID:</strong>
  <td><%= @list.user_id %></td>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>